version: 0.1.0.{build}

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"

platform:
  - x64
  - x86
  - mingw

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - if /I "%platform%"=="mingw" set HR_TARGET=mingw
  - if /I "%platform%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - hererocks env --%LUA% --target %HR_TARGET% -rlatest
  - call env\bin\activate

build_script:
  - luarocks make rockspecs\winreg-scm-0.rockspec

test_script:
  - cd test
  - lua test_1.lua
  - lua test_5_1_5.lua
  - lua test_5_1_6.lua
  - lua test_5_1_8.lua
  - lua test_5_1_9.lua
  - lua test_5_1_10.lua
  - lua test_5_1_13.lua
  - lua test_5_1_14.lua
